#data path
content_path: "./data/content_coco"
style_path: "./data/style/van_gogh/000.jpg"

#output path
output_path: "./output"

#pretrained diffusion model path
pretrained_model_path: "./models/checkpoints/512x512_diffusion.pt"

#run parameters
run_id: "test_run"
run_mode: "style_removal" #options: "style_removal", "style_transfer"
# run_mode: "style_transfer"

device: "cuda" #options: "cpu", "cuda"
image_size: 512

#diffusion model parameters
diffusion_num_timesteps: 1000
diffusion_beta_start: 0.0001
diffusion_beta_end: 0.02

#style removal specific parameters
t_remov: 603
style_removal_s_for: 40
style_removal_s_rev: 6

#style transfer specific parameters
#content and style image locations. these are the output of the style removal module.
content_gray_path: "./output/test_run/content_processed/"
content_latent_path: "./output/test_run/content_latents/"
style_color_path: "./data/style/van_gogh/000.jpg"
style_gray_path: "./output/test_run/style_processed/style.pt"
style_latent_path: "./output/test_run/style_latents/style.pt"
generated_dir: "./output/test_run/content_stylized"

t_trans: 601
style_transfer_s_for: 40
style_transfer_s_rev: 6
k: 5 #epochs
k_s: 50 #number of repetitions for style construction loss optimization
lr: 0.000004 #learning rate
lr_multiplier: 1.2 #learning rate linear multiplier per epoch
lambda_style: 1 #hyperparameter for style reconstruction loss
lambda_l1: 10 #hyperparameter for style disentanglement loss
lambda_dir: 6 #hyperparameter for style disentanglement loss
precompute_latents: True #set False if latents are already precomputed